version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/dev-bins"
      - "/ci/xtask"
      - "/programs/sbf"
    schedule:
      interval: daily
      time: "01:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 6
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
