[package]
name = "solana-svm-test-harness-syscall"
description = "Solana SVM test harness for syscall execution."
documentation = "https://docs.rs/solana-svm-test-harness-syscall"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = false

[features]
agave-unstable-api = []
dummy-for-ci-check = ["fuzz"]
fuzz = [
    "dep:prost",
    "solana-pubkey/default",
    "solana-svm-test-harness-fixture/fuzz",
    "solana-svm-test-harness-instr/fuzz",
]

[dependencies]
agave-feature-set = { workspace = true }
agave-precompiles = { workspace = true }
agave-syscalls = { workspace = true }
bincode = { workspace = true }
prost = { workspace = true, optional = true }
solana-account = { workspace = true }
solana-compute-budget = { workspace = true }
solana-instruction = { workspace = true }
solana-instruction-error = { workspace = true, features = ["serde"] }
solana-poseidon = { workspace = true }
solana-precompile-error = { workspace = true }
solana-program-runtime = { workspace = true }
solana-pubkey = { workspace = true }
solana-sbpf = { workspace = true }
solana-stable-layout = { workspace = true }
solana-svm-callback = { workspace = true }
solana-svm-feature-set = { workspace = true }
solana-svm-log-collector = { workspace = true }
solana-svm-test-harness-fixture = { workspace = true }
solana-svm-test-harness-instr = { workspace = true }
solana-transaction-context = { workspace = true }

[lints]
workspace = true
